#!/bin/sh

export SHARED_BASE="/data"

if [ "x$1" = "xpkg" ]; then
        set -e

        export USER_UID=${USER_UID}
        export BRANCH=${BRANCH}

        ssh-keyscan -t rsa github.com >> /etc/ssh/ssh_known_hosts
        git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
        go env -w GOPRIVATE=github.com/vpngen

        git clone ssh://git@github.com/vpngen/keydesk
        if [ "x" != "x${BRANCH}" ]; then
                git -C keydesk checkout ${BRANCH}
        fi

        keydesk/debpkg/src/build.sh

        exit 0
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)

docker run --rm \
        -v $(readlink -f $SSH_AUTH_SOCK):/ssh-agent \
        -e SSH_AUTH_SOCK=/ssh-agent \
        -e USER_UID=$(id -u) \
        -e BRANCH=${BRANCH} \
        -v ${PWD}:"${SHARED_BASE}" \
        golang:1.19 "${SHARED_BASE}/build" pkg

